/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.ReservaController;
import java.awt.Dimension;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import Controller.MenuPrincipalController;

/**
 *
 * @author FelipeCruz
 */
public class Reserva extends javax.swing.JFrame {


    private final ReservaController controller;

    /**
     * Creates new form Agenda
     */
    public Reserva() {
        initComponents();
        controller = new ReservaController(this);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelReserva = new javax.swing.JLabel();
        ButtonVoltar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableAgendamentos = new javax.swing.JTable();
        LabelAgendaFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelReserva.setFont(new java.awt.Font("Liberation Sans", 1, 36)); // NOI18N
        LabelReserva.setForeground(new java.awt.Color(255, 255, 255));
        LabelReserva.setText("Reservas");
        getContentPane().add(LabelReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 200, 60));

        ButtonVoltar.setBackground(new java.awt.Color(0, 153, 51));
        ButtonVoltar.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        ButtonVoltar.setText("Voltar");
        ButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(ButtonVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 420, 210, 50));

        TableAgendamentos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "05/12/2020", "08:00", "Felipe"}
            },
            new String [] {
                "Id", "Data", "Hora", "Observação"
            }
        ));
        TableAgendamentos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(TableAgendamentos);
        if (TableAgendamentos.getColumnModel().getColumnCount() > 0) {
            TableAgendamentos.getColumnModel().getColumn(3).setPreferredWidth(300);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 530, 130));

        LabelAgendaFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/imagens/fundoreserva.jpeg"))); // NOI18N
        getContentPane().add(LabelAgendaFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -60, 830, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVoltarActionPerformed
     controller.navegarParaMenuPrincipal();
    }//GEN-LAST:event_ButtonVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Agenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
          /*   new Agenda().setVisible(true);  VERIFICAR DEPOIS*/ 
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonVoltar;
    private javax.swing.JLabel LabelAgendaFundo;
    private javax.swing.JLabel LabelReserva;
    private javax.swing.JTable TableAgendamentos;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private void layoutTabela() {

        this.TableAgendamentos.getColumnModel().getColumn(0).setPreferredWidth(45);
        this.TableAgendamentos.getColumnModel().getColumn(1).setPreferredWidth(200);
        this.TableAgendamentos.getColumnModel().getColumn(2).setPreferredWidth(200);
        this.TableAgendamentos.getColumnModel().getColumn(3).setPreferredWidth(300);
    }
    /*
    public JTable getTableAgendamentos() {
        return TableAgendamentos;
    }

    public void setTableAgendamentos(JTable TableAgendamentos) {
        this.TableAgendamentos = TableAgendamentos;
    }
*/

    
}
